# Generated by Django 5.0 on 2023-12-10 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LittleLemon', '0002_booking_reservation_date_booking_reservation_slot'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='last_name',
        ),
    ]
