# Generated by Django 5.0 on 2023-12-10 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LittleLemon', '0004_alter_booking_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='comment',
            field=models.CharField(max_length=1000),
        ),
    ]
